name: Sample Pipeline

on:
  push:

jobs:
  checkmarx:
    runs-on: ubuntu-latest
    steps:
      - run: echo "checkmarx"
      
  docker_image:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
         - run: |
             cat /etc/os-release
        
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "sonarqube"
          echo "multi line commands"

  unit-test:
    runs-on: ubuntu-latest
    needs: [checkmarx,sonarqube,docker_image]
    steps:
      - run: echo "unit test"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - run: echo "deploy dev"

  service-level-jmeter:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    steps:
      - run: echo "service-level-jmeter"

  contract-test:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    steps:
      - run: echo "contract-test"
      
  deploy-test:
    runs-on: ubuntu-latest
    needs: [service-level-jmeter, contract-test]
    steps:
      - run: echo "cdeploy-test"

  performance-test:
    runs-on: ubuntu-latest
    needs: [deploy-test]
    steps:
      - run: echo "performance-test"

  UI-test:
    runs-on: ubuntu-latest
    needs: [deploy-test]
    steps:
      - run: echo "UI-test"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [performance-test, UI-test]
    steps:
      - run: echo "deploy prod"

    
