name: Sample Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Hello world
      run: echo "Hello, World!"

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Testt
      run: echo "Test"


